### PR TITLE
feat(go): add go target

### PR DESCRIPTION
**Pull request by rubenfonseca**
We're using Go for our CDK project, and would love to use this in our project too!

### CODE REVIEW

**Comment by mbonig** [comment]
Hey! Thanks for contributing. I've never published to GO before so I'll take a stab at it.

**Comment by rubenfonseca** [comment]
Great! I see that you've added Python already, so adding Go should be similar! Thank you!

**Comment by mbonig** [comment]
@rubenfonseca Please rebase from main when you have a moment...

**Comment by rubenfonseca** [comment]
@mbonig done!

**Review by mbonig — APPROVED** [review]

**Comment by mbonig** [comment]
Thanks for the contribution. Looks like it's been published. Can you give it a try and open Issues if there are problems?

**Pull request merged**
