### PR TITLE
fix: added missing 'from'

### PR DESCRIPTION
**Pull request by dmytrokosiachenko**
Fixes # missing 'from' in the generated State Machine .ts file.

### CODE REVIEW

**Comment by mbonig** [comment]
Thanks for catching that and submitting a PR. I believe a test will need to be updated as well before this will build.

**Review by mbonig — CHANGES_REQUESTED** [review]
A test will need to be updated.

**Comment by dmytrokosiachenko** [comment]
done, please approve workflow.

**Review by mbonig — APPROVED** [review]

**Comment by mbonig** [comment]
Thank you for the contribution!

**Pull request merged**
